title: Expressive Acoustic Guitar Sound Synthesis With An Instrument-Specific Input Representation And Diffusion Outpainting
description: Hounsu Kim, Soonbeom Choi, Juhan Nam
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman